suspendfile = /etc/fcron/fcron.suspend
fcronallow = /etc/fcron/fcron.allow
fcrondeny = /etc/fcron/fcron.deny
shell = /usr/bin/nu
editor = /usr/bin/nvim
maildisplayname = Fcron Daemon
# TODO: add sendmail
