"theme" = "main"

"theme.main.static_bar" = false
"theme.main.default_indicator" = " "
"theme.main.bar_style.bg" = "■"
"theme.main.bar_style.fg" = "■"
"theme.main.bar_style.indicator" = "■"
"theme.main.bar_style.top" = ""
"theme.main.bar_style.bottom" = ""
"theme.main.bar_low.front" = 0
"theme.main.bar_low.back" = -1
"theme.main.volume_low" = 12
"theme.main.bar_mid.front" = 0
"theme.main.bar_mid.back" = -1
"theme.main.volume_mid" = 4
"theme.main.bar_high.front" = 0
"theme.main.bar_high.back" = -1
"theme.main.volume_high" = 4
"theme.main.volume_peak" = 9
"theme.main.volume_indicator" = 1
"theme.main.selected" = 1
"theme.main.default" = 15
"theme.main.border" = -1
"theme.main.dropdown.selected_text" = 5
"theme.main.dropdown.selected" = -1
"theme.main.dropdown.unselected" = 7

# keybinds
"keycode.63" = "help" # ?
"keycode.27" = "quit" # escape
"keycode.113" = "quit" # q
"keycode.13" = "select" # enter
"keycode.100" = "set_default" # d

"keycode.108" = "volume_up" # l
"keycode.104" = "volume_down" # h
"keycode.261" = "volume_up" # arrow right
"keycode.260" = "volume_down" # arrow left

"keycode.103" = "move_first" # g
"keycode.71" = "move_last" # G
"keycode.107" = "move_up" # k
"keycode.106" = "move_down" # j
"keycode.259" = "move_up" # arrow up
"keycode.258" = "move_down" # arrow down

"keycode.97" = "tab_playback" # a
"keycode.111" = "tab_recording" # o
"keycode.101" = "tab_output" # e
"keycode.117" = "tab_input" # u
"keycode.105" = "tab_config" # i

"keycode.109" = "mute" # m
"keycode.49" = "set_volume_10" # 1
"keycode.50" = "set_volume_20" # 2
"keycode.51" = "set_volume_30" # 3
"keycode.52" = "set_volume_40" # 4
"keycode.53" = "set_volume_50" # 5
"keycode.54" = "set_volume_60" # 6
"keycode.55" = "set_volume_70" # 7
"keycode.56" = "set_volume_80" # 8
"keycode.57" = "set_volume_90" # 9
"keycode.48" = "set_volume_100" # 0
