# fontsize
keybind = ctrl+alt+==increase_font_size:1
keybind = ctrl+alt+-=decrease_font_size:1
keybind = ctrl+alt+shift+==reset_font_size

# sccoll
keybind = alt+ctrl+u=scroll_page_fractional:-0.5
keybind = alt+ctrl+d=scroll_page_fractional:0.5

# selection
keybind = shift+up=adjust_selection:up
keybind = shift+down=adjust_selection:down
keybind = shift+right=adjust_selection:right
keybind = shift+left=adjust_selection:left
keybind = ctrl+shift+a=select_all
keybind = ctrl+shift+c=copy_to_clipboard
keybind = ctrl+shift+v=paste_from_clipboard

# other
keybind = alt+g>r=reload_config
keybind = alt+g>p=toggle_command_palette
