[options]
RootDir = /
DBPath = /var/lib/pacman/
CacheDir = /var/cache/pacman/pkg/
HookDir = /etc/pacman.d/hooks/
HookDir = /home/armen/.config/pacman/hooks/
GPGDir = /etc/pacman.d/gnupg/
LogFile = /var/log/pacman.log
Architecture = auto
CleanMethod = KeepInstalled
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
RemoteFileSigLevel = Optional
ParallelDownloads = 5
DownloadUser = alpm
CheckSpace
VerbosePkgLists
Color
# XferCommand
# NoProgressBar
# DisableDownloadTimeout
# DisableSandbox
# DisableSandboxFilesystem
# DisableSandboxSyscalls
# UseSyslog

HoldPkg = pacman glibc
IgnorePkg =
IgnoreGroup =
NoUpgrade =
NoExtract =

[core]
Include = /etc/pacman.d/mirrorlist
Usage = All

[extra]
Include = /etc/pacman.d/mirrorlist
Usage = All

[multilib]
Include = /etc/pacman.d/mirrorlist
Usage = All
