[advice]
	addEmbeddedRepo = true
	addEmptyPathspec = false
	addIgnoredFile = true
	amWorkDir = true
	ambiguousFetchRefspec = true
	checkoutAmbiguousRemoteBranchName = true
	commitBeforeMerge = true
	detachedHead = true
	diverging = true
	fetchShowForcedUpdates = true
	forceDeleteBranch = true
	ignoredHook = true
	implicitIdentity = true
	mergeConflict = true
	nestedTag = true
	pushAlreadyExists = true
	pushFetchFirst = true
	pushNeedsForce = true
	pushNonFFCurrent = true
	pushNonFFMatching = true
	pushRefNeedsUpdate = true
	pushUnqualifiedRefname = true
	pushUpdateRejected = true
	rebaseTodoError = true
	refSyntax = true
	resetNoRefresh = true
	resolveConflict = true
	rmHints = true
	sequencerInUse = true
	skippedCherryPicks = true
	sparseIndexExpanded = true
	statusAheadBehind = true
	statusHints = true
	statusUoption = true
	submoduleAlternateErrorStrategyDie = true
	submoduleMergeConflict = true
	submodulesNotUpdated = true
	suggestDetachingHead = true
	updateSparsePath = true
	waitingForEditor = true
	worktreeAddOrphan = true
