[core]
	fileMode = true
	hideDotFiles = false
	ignoreCase = false
	precomposeUnicode = true
	protectHFS = true
	protectNTFS = true
	fsmonitor = false
	fsmonitorHookVersion = 2
	trustctime = true
	splitIndex = false
	untrackedCache = keep
	checkStat = default
	quotePath = false
	eol = native
	autocrlf = input
	safecrlf = false
	checkRoundtripEncoding = SHIFT-JIS
	symlinks = true
	sshCommand = ssh
	ignoreStat = false
	bare = false
	lockfilePid = true
	logAllRefUpdates = always
	sharedRepository = false
	warnAmbiguousRefs = true
	compression = -1
	looseCompression = 1
	bigFileThreshold = 512m
	excludesFile = $XDG_CONFIG_HOME/git/ignore

	#commentChar = "#"
	#filesRefLockTimeout = 100
	#packedRefsTimeout = 1000
	#whitespace = blank-at-eol,space-before-tab,blank-at-eof
	#fsync = committed,-loose-object
	#fsyncMethod = fsync
	#fsyncObjectFiles = false
	#preloadIndex = true
	#commitGraph = true
	#useReplaceRefs = true
	#multiPackIndex = true
	#sparseCheckout = false
	#sparseCheckoutCone = true
	#abbrev = auto
	#maxTreeDepth = 2048
	#lockfilePid = false
	#editor = nvim
	#pager = less
