[blame]
	blankBoundary = false
	coloring = highlightRecent
	date = iso
	showEmail = false
	showRoot = true
	markUnblamableLines = true
	markIgnoredLines = true

[branch]
	autoSetupMerge = true
	autoSetupRebase = never
	sort = -committerdate

[browser "zen"]
	cmd = /sbin/zen-browser

[checkout]
	defaultRemote = origin
	guess = true
	workers = 0
	thresholdForParallelism = 100

[clone]
	defaultRemoteName = origin
	rejectShallow = false
	filterSubmodules = true

[column]
	ui = auto row
	branch = auto row
	clean = auto row
	status = auto row
	tag = auto row

[commit]
	cleanup = default
	gpgSign = false #TODO set to true
	status = true
	template = ~/.config/git/.gitmessage
	verbose = false
