## GAMESCOPE TODO
## Display the status of FSR (only works in gamescope)
# fsr
## Hides the sharpness info for the `fsr` option (only available in gamescope)
# hide_fsr_sharpness
## Shows the graph of gamescope app frametimes and latency (only on gamescope obviously)
# debug
## Display the status of HDR (only works in gamescope)
# hdr
## Display the current refresh rate (only works in gamescope)
# refresh_rate


## PERF
fps_limit=0
#fps_limit_method=late
#vsync=
#gl_vsync=
#picmip=
#af=
#bicubic
#trilinear
#retro


## QUICK
#preset=-1
#full
#fps_only

## GPU
gpu_text=GPU
gpu_list=0,1
gpu_stats
gpu_temp
gpu_core_clock
gpu_power
gpu_power_limit
gpu_load_change
gpu_load_value=60,90
gpu_load_color=50fa7b,ffb86c,FF2E66
gpu_fan
# gpu_junction_temp
# gpu_mem_temp
# gpu_mem_clock
# gpu_voltage
# gpu_efficiency


## CPU
cpu_text=CPU
cpu_stats
cpu_temp
cpu_power
cpu_mhz
cpu_load_change
cpu_load_value=60,90
cpu_load_color=50fa7b,ffb86c,FF2E66
core_load
core_load_change
core_bars
core_type
#cpu_efficiency


## MEM
vram
ram
swap
procmem
proc_vram
#procmem_shared
#procmem_virt
#io_read
#io_write

## FONT
font_size=26
font_scale=1.0
font_size_text=26
font_scale_media_player=1.0
font_file=/usr/share/fonts/TTF/JetBrainsMonoNerdFont-Bold.ttf
font_file_text=/usr/share/fonts/TTF/JetBrainsMonoNerdFont-Bold.ttf
#no_small_font
#font_glyph_ranges=korean,chinese,chinese_simplified,japanese,cyrillic,thai,vietnamese,latin_ext_a,latin_ext_b
#text_outline
#text_outline_color = 333333
#text_outline_thickness = 0.1

## FPS
fps
fps_sampling_period=500
fps_color_change
fps_value=40,150
fps_color=FF2E66,ffb86c,50fa7b
frametime
fps_metrics=avg,0.01,0.1
throttling_status_graph
frame_timing
frame_timing_detailed
#fps_text=FPS
#frame_count
#throttling_status
#dynamic_frame_timing
#histogram

## TIME
#time
#time_no_label
#time_format=%H%M.%S

## MEDIA
#media_player
#media_player_name=
#media_player_format=title,artist,album

## BATTERY
#battery
#battery_icon
#device_battery=gamepad,mouse
#device_battery_icon
#battery_watt
#battery_time

## FCAT
#fcat
#fcat_overlay_width=20
#fcat_screen_edge=0

## OPENGL
gl_size_query=viewport
#gl_bind_framebuffer
#gl_dont_flip=1

## OTHER
gamemode
vkbasalt
present_mode
mangoapp_steam
resolution
display_server
vulkan_driver
engine_version
gpu_name
arch
fan
#custom_text_center=
#show_fps_limit
#version
#engine_short_names
#wine
#exec_name
#winesync
#graphs=
#temp_fahrenheit
#flip_efficiency
#network=
#custom_text=
#exec=
#fex_stats
#pci_dev=0000:03:00.0
#blacklist=
#control=
#ftrace=histogram/drm_vblank_event+linegraph/devfreq_monitor/freq

## UI
position=top-left
offset_x=0
offset_y=0
round_corners=7
hud_no_margin
hud_compact
table_columns=4
cellpadding_y=-0.085
background_alpha=0.7
alpha=1.0
#horizontal
#horizontal_stretch
#no_display
#width=0
#height=0

text_color=FFFFFF
gpu_color=50fa7b
cpu_color=ffffa5
vram_color=d6acff
ram_color=d6acff
engine_color=a4ffff
frametime_color=FF2E66
background_color=1a102e
wine_color=B78F71
horizontal_separator_color=ffffff
#network_color=
#battery_color
#media_player_color=
#io_color=

## KEYBINDS
toggle_hud=Shift_L+F1
reset_fps_metrics=Shift_L+F2
toggle_logging=Shift_L+F3
toggle_hud_position=Shift_L+F4
toggle_preset=Shift_L+F5
toggle_fps_limit=Shift_L+F6
reload_cfg=Shift_L+F7
#upload_log=

## LOG
autostart_log=10
log_duration=0
log_interval=0
output_folder=/home/armen/.local/share
output_file=mangohud.log
permit_upload=0
benchmark_percentiles=97,AVG,1,0.1
#log_versioning
#upload_logs
