bindel = ,XF86MonBrightnessUp, exec, hyp_backlight increase --notify 10
bindel = ,XF86MonBrightnessDown, exec, hyp_backlight decrease --notify 10
bindel = ,XF86KbdBrightnessUp, exec, hyp_backlight increase --name asus::kbd_backlight --notify 33
bindel = ,XF86KbdBrightnessDown, exec, hyp_backlight decrease --name asus::kbd_backlight --notify 33

bind = SUPER, B, exec, hyp_backlight
bind = SUPER SHIFT, B, exec, hyp_blue_filter
