# VWS
## FOCUS PRIMARY
bind = SUPER, 1, exec, hyp_flow focus 0 primary
bind = SUPER, 2, exec, hyp_flow focus 1 primary
bind = SUPER, 3, exec, hyp_flow focus 2 primary
bind = SUPER, 4, exec, hyp_flow focus 3 primary
bind = SUPER, 5, exec, hyp_flow focus 4 primary
bind = SUPER, 6, exec, hyp_flow focus 5 primary
bind = SUPER, 7, exec, hyp_flow focus 6 primary
bind = SUPER, 8, exec, hyp_flow focus 7 primary
bind = SUPER, 9, exec, hyp_flow focus 8 primary
bind = SUPER, 0, exec, hyp_flow focus 9 primary

## PULL
bind = SUPER SHIFT, 1, exec, hyp_flow pull 0 primary
bind = SUPER SHIFT, 2, exec, hyp_flow pull 1 primary
bind = SUPER SHIFT, 3, exec, hyp_flow pull 2 primary
bind = SUPER SHIFT, 4, exec, hyp_flow pull 3 primary
bind = SUPER SHIFT, 5, exec, hyp_flow pull 4 primary
bind = SUPER SHIFT, 6, exec, hyp_flow pull 5 primary
bind = SUPER SHIFT, 7, exec, hyp_flow pull 6 primary
bind = SUPER SHIFT, 8, exec, hyp_flow pull 7 primary
bind = SUPER SHIFT, 9, exec, hyp_flow pull 8 primary
bind = SUPER SHIFT, 0, exec, hyp_flow pull 9 primary

## VWS SUBMAP
bind = SUPER, W, submap, vws
submap = vws, reset

### FOCUS SECONDARY
bind = , 1, exec, hyp_flow focus 0 secondary
bind = , 2, exec, hyp_flow focus 1 secondary
bind = , 3, exec, hyp_flow focus 2 secondary
bind = , 4, exec, hyp_flow focus 3 secondary
bind = , 5, exec, hyp_flow focus 4 secondary
bind = , 6, exec, hyp_flow focus 5 secondary
bind = , 7, exec, hyp_flow focus 6 secondary
bind = , 8, exec, hyp_flow focus 7 secondary
bind = , 9, exec, hyp_flow focus 8 secondary
bind = , 0, exec, hyp_flow focus 9 secondary

### CHANGE COL
bind = SHIFT, 1, exec, hyp_flow change_vws_col 0
bind = SHIFT, 2, exec, hyp_flow change_vws_col 1
bind = SHIFT, 3, exec, hyp_flow change_vws_col 2
bind = SHIFT, 4, exec, hyp_flow change_vws_col 3
bind = SHIFT, 5, exec, hyp_flow change_vws_col 4
bind = SHIFT, 6, exec, hyp_flow change_vws_col 5
bind = SHIFT, 7, exec, hyp_flow change_vws_col 6
bind = SHIFT, 8, exec, hyp_flow change_vws_col 7
bind = SHIFT, 9, exec, hyp_flow change_vws_col 8
bind = SHIFT, 0, exec, hyp_flow change_vws_col 9

### OTHER
bind = , p, exec, hyp_flow push
bind = , s, exec, hyp_flow secondary_vws

bind = SUPER, ESCAPE, submap, reset
submap = reset

# WINDOW
## FOCUS
bind = SUPER, L, exec, hyp_window focus r
bind = SUPER, H, exec, hyp_window focus l
bind = SUPER, K, exec, hyp_window focus u
bind = SUPER, J, exec, hyp_window focus d

## MOVE
bind = SUPER SHIFT, L, exec, hyp_window move r
bind = SUPER SHIFT, H, exec, hyp_window move l
bind = SUPER SHIFT, K, exec, hyp_window move u
bind = SUPER SHIFT, J, exec, hyp_window move d
bindm = SUPER, mouse:272, movewindow

## REZISE
bind = SUPER ALT, L, exec, hyp_window resize r
bind = SUPER ALT, H, exec, hyp_window resize l
bind = SUPER ALT, K, exec, hyp_window resize u
bind = SUPER ALT, J, exec, hyp_window resize d
bindm = SUPER, mouse:273, resizewindow


## OTHER
bind = SUPER SHIFT, F, exec, hyp_window toggle_float
bind = SUPER, F, fullscreen
bind = SUPER, X, killactive,
