# brightness
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 10%-
bindel = ,XF86KbdBrightnessUp, exec, brightnessctl -d asus::kbd_backlight set 1+
bindel = ,XF86KbdBrightnessDown, exec, brightnessctl -d asus::kbd_backlight set 1-
