bind = SUPER SHIFT, N, exec, hyp_notification close

bind = SUPER, N, submap, notification
submap = notification, reset

bind = , T, exec, hyp_notification
bind = SHIFT, X, exec, hyp_notification close --all
bind = , X, exec, hyp_notification close
bind = , L, exec, hyp_notification pause --increase
bind = , H, exec, hyp_notification pause --decrease
bind = , O, exec, hyp_notification pause --toggle


bind = SUPER, ESCAPE, submap, reset
submap = reset
