# FOCUS
bind = SUPER, L, movefocus, r
bind = SUPER, H, movefocus, l
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# MOVE
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

# SPLITS
bind = SUPER SHIFT, S, togglesplit, 

# REZISE
bind = SUPER ALT, L, resizeactive, 10% 0%
bind = SUPER ALT, H, resizeactive, -10% 0%
bind = SUPER ALT, K, resizeactive, 0% -10%
bind = SUPER ALT, J, resizeactive, 0% 10%
bindm = SUPER, mouse:273, resizewindow

# MOVE FLOATING
bind = SUPER CTRL, L, moveactive, 10% 0%
bind = SUPER CTRL, H, moveactive, -10% 0%
bind = SUPER CTRL, K, moveactive, 0% -30%
bind = SUPER CTRL, J, moveactive, 0% 30%
bindm = SUPER, mouse:272, movewindow

# OTHER
bind = SUPER, F, fullscreen
bind = SUPER, X, killactive,
