# FOCUS
bind = SUPER, 1, exec, hyp_workspace focus 1
bind = SUPER, 2, exec, hyp_workspace focus 2
bind = SUPER, 3, exec, hyp_workspace focus 3
bind = SUPER, 4, exec, hyp_workspace focus 4
bind = SUPER, 5, exec, hyp_workspace focus 5
bind = SUPER, 6, exec, hyp_workspace focus 6
bind = SUPER, 7, exec, hyp_workspace focus 7
bind = SUPER, 8, exec, hyp_workspace focus 8
bind = SUPER, 9, exec, hyp_workspace focus 9
bind = SUPER, 0, exec, hyp_workspace focus 10

# MOVE
bind = SUPER SHIFT, 1, exec, hyp_workspace move 1
bind = SUPER SHIFT, 2, exec, hyp_workspace move 2
bind = SUPER SHIFT, 3, exec, hyp_workspace move 3
bind = SUPER SHIFT, 4, exec, hyp_workspace move 4
bind = SUPER SHIFT, 5, exec, hyp_workspace move 5
bind = SUPER SHIFT, 6, exec, hyp_workspace move 6
bind = SUPER SHIFT, 7, exec, hyp_workspace move 7
bind = SUPER SHIFT, 8, exec, hyp_workspace move 8
bind = SUPER SHIFT, 9, exec, hyp_workspace move 9
bind = SUPER SHIFT, 0, exec, hyp_workspace move 10
