require("options")
require("keymap")
require("per_project_config")
require("features.lazy_pm").init()
require("features.lsp").init()
require("features.project").init()
require("features.oil").init()
require("features.window").init()
