env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = PATH,\$PATH:/home/armen/.config/scripts
env = XDG_CONFIG_HOME,/home/armen/.config
env = XDG_DATA_HOME,/home/armen/.local/share
env = XDG_STATE_HOME,/home/armen/.local/state
env = XDG_CACHE_HOME,/home/armen/.cache
env = XDG_PICTURES_DIR,$HOME/Downloads

# card1 -> nvidia, card2 -> intel UHD
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card2
