env = XCURSOR_THEME,isla_coleman_neet
env = HYPRCURSOR_THEME,isla_coleman_neet
env = XCURSOR_SIZE,36
env = HYPRCURSOR_SIZE,36
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# card1 -> nvidia, card2 -> intel UHD
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card2
env = DRI_PRIME,1
