general {
	allow_tearing = true

	gaps_in = 2
	gaps_out = 5

	border_size = 2
	col.active_border = rgba(ff82cdff) rgba(f54242ff) 45deg
	col.inactive_border = rgba(595959aa)

	layout = dwindle
	no_focus_fallback = true

	resize_on_border = false
	allow_tearing = true

	snap {
		enabled = true
		monitor_gap = 50
		window_gap = 50
	}
}

