listener {
	timeout = 300 # 5min
	on-timeout = hyp_idle 1
	on-resume = hyp_idle 0
}

listener {
	timeout = 420 # 7min
	on-timeout = hyp_idle 2
	on-resume = hyp_idle 0
}

listener {
	timeout = 480 # 8min
	on-timeout = hyp_idle 3
	on-resume = hyp_idle 0
}
