source = ./envs.conf
source = ./constants.conf
source = ./monitors.conf
source = ./decoration.conf
source = ./inputs.conf
source = ./general.conf
source = ./misc.conf
source = ./animations.conf
source = ./others.conf
source = ./init_setup.conf
source = ./keybindings/main.conf
source = ./window_rules.conf
source = ./workspace_rules.conf
source = ./render.conf
