# Note
# time values are in seconds

listener {
  timeout = 600 
  on-timeout = hyp_idle 0
  on-resume = hyp_idle 0 -r
}

listener {
  timeout = 900 
  on-timeout = hyp_idle 1
  on-resume = hyp_idle 1 -r
}
