general {
	hide_cursor = true
	ignore_empty_input = true
	immediate_render = false
	text_trim = true
	fractional_scaling = 2
	screencopy_mode = 0
	fail_timeout = 5000
}

background {
	path = ~/personal/media/wallpapers/mountain_1.jpg
	blur_size = 4
	blur_passes = 3
	brightness = 0.8
	noise = 0
}

input-field {
	monitor =
	size = 650, 65
	position = 0, 0
	halign = center
	valign = center

	dots_size = 0.2
	dots_spacing = 0
	dots_center = true
	dots_rounding = 0
	dots_text_format = 🌀

	hide_input = false
	fade_on_empty = false
	invert_numlock = false
	swap_font_color = false
	font_color = rgb(255, 46, 102)
	font_family = JetBrainsMono Nerd Font
	placeholder_text = <span size = "30000">🧙🏻‍♂️</span> <span font_family="JetBrainsMono Nerd Font" rise='5000'><b>"Many may craft, few may create" Tell me child. Do you hold true to the <span size='20000'><u>virtues</u></span> of an engineer ?</b></span>
	fail_text = <span size="30000">🧙🏻‍♂️</span> <span font_family="JetBrainsMono Nerd Font" rise='5000'> <b><u>Unworthy SCUM</u>. <span size="30000">YOU!</span> shall not pass!</b></span>

	outline_thickness = 0
	rounding = 20
	inner_color = rgba(255, 240, 249, 0.8)
	check_color = rgb(33, 34, 44)
	fail_color = rgb(33, 34, 44)
}
