# windows
exec-once = [workspace 1] zen-browser
exec-once = [workspace 1] ghostty
exec-once = [workspace 2] ghostty
exec-once = [workspace 3] ghostty
exec-once = [workspace 4] ghostty


# background
exec-once = hyprpaper
exec-once = clipse -listen
exec-once = hypridle

