# setup
exec-once = hyp_init_setup

# background
exec-once = waybar
exec-once = hyprpaper
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = clipse -listen
exec-once = systemctl --user start hyprpolkitagent

