# SET
## tools
### screenshot
bind = SUPER, S, submap, screenshot
submap = screenshot

bind = SUPER, M, exec, hyp_screenshot output -a
bind = SUPER, W, exec, hyp_screenshot window -a
bind = SUPER SHIFT, M, exec, hyp_screenshot output
bind = SUPER SHIFT, W, exec, hyp_screenshot window 

bind = SUPER, ESCAPE, submap, reset
submap = reset

### other
bind = SUPER, T, exec, ghostty
bind = SUPER, SPACE, exec, tofi-drun | xargs hyprctl dispatch exec
binds = Super_L, C&P, exec, hyprpicker -na
bind = SUPER, V, exec, hyp_lunch_clipboard 
bind = SUPER SHIFT, E, exec, hyp_select_emoji ~/personal/emojies

## windows
bind = SUPER, L, movefocus, r
bind = SUPER, H, movefocus, l
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

bind = SUPER SHIFT, L, swapwindow, r
bind = SUPER SHIFT, H, swapwindow, l
bind = SUPER SHIFT, K, swapwindow, u
bind = SUPER SHIFT, J, swapwindow, d

bind = SUPER SHIFT, S, togglesplit, 

bind = SUPER ALT, L, resizeactive, 10% 0%
bind = SUPER ALT, H, resizeactive, -10% 0%
bind = SUPER ALT, K, resizeactive, 0% -10%
bind = SUPER ALT, J, resizeactive, 0% 10%

bind = SUPER CTRL, L, moveactive, 10% 0%
bind = SUPER CTRL, H, moveactive, -10% 0%
bind = SUPER CTRL, K, moveactive, 0% -30%
bind = SUPER CTRL, J, moveactive, 0% 30%

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, F, fullscreen
bind = SUPER, X, killactive,

# Function 
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 10%-
bindel = ,XF86KbdBrightnessUp, exec, brightnessctl -d asus::kbd_backlight set 1+
bindel = ,XF86KbdBrightnessDown, exec, brightnessctl -d asus::kbd_backlight set 1-

## others
bind = SUPER SHIFT, ESCAPE, exit
bind = SUPER SHIFT, C, movecursortocorner, 2

# IN-PROGRESS
bind = SUPER SHIFT, F, togglefloating,
#bind = SUPER, P, pseudo, # dwindle

## workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

bind = SUPER, M, togglespecialworkspace, magic
bind = SUPER SHIFT, M, movetoworkspace, special:magic

## ununderstood yet

# Move/resize windows with mainMod + LMB/RMB and dragging

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
