[general]
fullscreen = delay
min_icon_size = 40
max_icon_size = 300
icon_position = left
word_wrap = true
ellipsize = middle
alignment = left
hide_text = false
markup = full
timeout = 5s
default_icon = "~/.config/dunst/assets/3d_penguin.png"
