[urgency_low]
background = "#0d0b19e0"
foreground = "#fff0f9"
highlight = "#fff0f9, #fff0f9"
frame_color = "#B78F71"
format = "<span color='#ead3c1'><b>%a: %s</b></span>\n<span color='#6272a4'></span>\n%b"
fullscreen = delay
override_pause_level = 0

[urgency_normal]
background = "#0d0b19e0"
foreground = "#fff0f9"
highlight = "#a4ffff, #00BEDB"
frame_color = "#a4ffff"
format = "<span color='#00BEDB'><b>%a: %s</b></span>\n<span color='#6272a4'></span>\n%b"
fullscreen = delay
override_pause_level = 50

[urgency_critical]
background = "#0d0b19e0"
foreground = "#fff0f9"
highlight = "#ff7aca, #ff2e66"
frame_color = "#FF2E66"
format = "<span color='#FF5C87'><b>%a: %s</b></span>\n<span color='#6272a4'></span>\n%b"
fullscreen = show
override_pause_level = 90
