# copy mode
bind -N 'enter copy mode' -n M-c 'copy-mode; send -X middle-line'
bind -N 'exit copy mode' -T copy-mode-vi Escape send-keys -X cancel
bind -N 'copy selection' -T copy-mode-vi y send -X copy-selection
bind -N 'go to previous prompt' -T copy-mode-vi C-p send -X previous-prompt
bind -N 'go to next prompt' -T copy-mode-vi C-n send -X next-prompt

## selection
bind -N 'start normal selection' -T copy-mode-vi v send -X begin-selection
bind -N 'start block selection' -T copy-mode-vi C-v send -X rectangle-toggle
bind -N 'select current word' -T copy-mode-vi i send -X select-word

## scroll
bind -N 'scroll up' -T copy-mode-vi C-k send -X scroll-up
bind -N 'scroll down' -T copy-mode-vi C-j send -X scroll-down
bind -N 'scroll up half page' -T copy-mode-vi C-u 'send -X halfpage-up; send -X middle-line'
bind -N 'scroll down half page' -T copy-mode-vi C-d 'send -X halfpage-down; send -X middle-line'

bind -N 'scroll up' -n C-k if-shell "$is_vim" 'send-keys C-k' 'copy-mode; send -X scroll-up'
bind -N 'scroll down' -n C-j if-shell "$is_vim" 'send-keys C-j' 'copy-mode; send -X scroll-down'
bind -N 'scroll up half page' -n C-u if-shell "$is_vim" 'send-keys C-u' 'copy-mode; send -X halfpage-up; send -X middle-line'
bind -N 'scroll down half page' -n C-d if-shell "$is_vim" 'send-keys C-d' 'copy-mode; send -X halfpage-down; send -X middle-line'
