# create/destroy panes
bind -N 'split window vertically' -n M-v if-shell "$is_vim" 'send-keys M-v' 'split-window -v'
bind -N 'split window horizontally' -n M-z if-shell "$is_vim" 'send-keys M-z' 'split-window -h'
bind -N 'kill pane' -n M-x if-shell "$is_vim" 'send-keys M-x' 'kill-pane'

## force create panes
bind -N 'force split window vertically' M-v split-window -v
bind -N 'force split window horizontally' M-z split-window -h


# focus pane
## normal mode
bind -N 'focus below pane' -n M-j if-shell "$is_vim" 'send-keys M-j' 'select-pane -D'
bind -N 'focus upper pane' -n M-k if-shell "$is_vim" 'send-keys M-k' 'select-pane -U'
bind -N 'focus right pane' -n M-l if-shell "$is_vim" 'send-keys M-l' 'select-pane -R'
bind -N 'focus left pane' -n M-h if-shell "$is_vim" 'send-keys M-h' 'select-pane -L'
bind -N 'focus previous pane' -n M-O if-shell "$is_vim" 'send-keys M-O' 'select-pane -l'

## force focus pane
bind -N 'force focus below pane' M-j select-pane -D
bind -N 'force focus upper pane' M-k select-pane -U
bind -N 'force focus right pane' M-l select-pane -R
bind -N 'force focus left pane' M-h select-pane -L

# swap panes
## normal mode
bind -N 'swap with below pane' -n M-J if-shell "$is_vim" 'send-keys M-J' 'swap-pane -d -t "{down-of}"'
bind -N 'swap with upper pane' -n M-K if-shell "$is_vim" 'send-keys M-K' 'swap-pane -d -t "{up-of}"'
bind -N 'swap with right pane' -n M-L if-shell "$is_vim" 'send-keys M-L' 'swap-pane -d -t "{right-of}"'
bind -N 'swap with left pane' -n M-H if-shell "$is_vim" 'send-keys M-H' 'swap-pane -d -t "{left-of}"'

## force swap pane
bind -N 'force swap with below pane' M-J swap-pane -d -t '{down-of}'
bind -N 'force swap with upper pane' M-K swap-pane -d -t '{up-of}'
bind -N 'force swap with right pane' M-L swap-pane -d -t '{right-of}'
bind -N 'force swap with left pane' M-H swap-pane -d -t '{left-of}'

# resize panes
## normal mode
bind -N 'resize pane downward' -n M-C-j if-shell "$is_vim" 'send-keys M-C-j' 'resize-pane -D 3'
bind -N 'resize pane upward' -n M-C-k if-shell "$is_vim" 'send-keys M-C-k' 'resize-pane -U 3'
bind -N 'resize pane to the right' -n M-C-l if-shell "$is_vim" 'send-keys M-C-l' 'resize-pane -R 5'
bind -N 'resize pane to the left' -n M-C-h if-shell "$is_vim" 'send-keys M-C-h' 'resize-pane -L 5'
bind -N 'toggle pane zoom' -n M-C-z if-shell "$is_vim" 'send-keys M-C-z' 'resize-pane -Z'
bind -N 'equlaize panes' -n M-= if-shell "$is_vim" 'send-keys M-=' 'select-layout tiled'

## force resize pane
bind -N 'force resize pane downward' M-C-j resize-pane -D 3
bind -N 'force resize pane upward' M-C-k resize-pane -U 3
bind -N 'force resize pane to the right' M-C-l resize-pane -R 5
bind -N 'force resize pane to the left' M-C-h resize-pane -L 5
bind -N 'force toggle pane zoom' M-C-z resize-pane -Z

# switch pane to window
bind -N 'switch pane to 1st window' 1 join-pane -h -t :1
bind -N 'switch pane to 2nd window' 2 join-pane -h -t :2
bind -N 'switch pane to 3rd window' 2 join-pane -h -t :3
bind -N 'switch pane to 4th window' 2 join-pane -h -t :4
bind -N 'switch pane to 5th window' 2 join-pane -h -t :5
bind -N 'switch pane to 6th window' 2 join-pane -h -t :6
bind -N 'switch pane to 7th window' 2 join-pane -h -t :7
bind -N 'switch pane to 8th window' 2 join-pane -h -t :8
bind -N 'switch pane to 9th window' 2 join-pane -h -t :9
bind -N 'switch pane to 10th window' 2 join-pane -h -t :10

bind -N 'move other pane in next window' b break-pane -b
