# create windows
bind -N 'create new window' -n M-n neww

# select window
bind -N 'select 1st window' -n M-1 select-window -t :1
bind -N 'select 2nd window' -n M-2 select-window -t :2
bind -N 'select 3rd window' -n M-3 select-window -t :3
bind -N 'select 4th window' -n M-4 select-window -t :4
bind -N 'select 5th window' -n M-5 select-window -t :5
bind -N 'select 6th window' -n M-6 select-window -t :6
bind -N 'select 7th window' -n M-7 select-window -t :7
bind -N 'select 8th window' -n M-8 select-window -t :8
bind -N 'select 9th window' -n M-9 select-window -t :9
bind -N 'select 10th window' -n M-0 select-window -t :10

# move windows
bind -N 'move 1st window' -n M-! run-shell 'tmx window move 1'
bind -N 'move 2nd window' -n M-@ run-shell 'tmx window move 2'
bind -N 'move 3rd window' -n M-# run-shell 'tmx window move 3'
bind -N 'move 4th window' -n M-$ run-shell 'tmx window move 4'
bind -N 'move 5th window' -n M-% run-shell 'tmx window move 5'
bind -N 'move 6th window' -n M-^ run-shell 'tmx window move 6'
bind -N 'move 7th window' -n M-& run-shell 'tmx window move 7'
bind -N 'move 8th window' -n M-* run-shell 'tmx window move 8'
bind -N 'move 9th window' -n M-( run-shell 'tmx window move 9'
bind -N 'move 10th window' -n M-) run-shell 'tmx window move 10'
