# normal mode
bind -N 'focus below pane' -n M-j \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-j' \
'select-pane -D'

bind -N 'focus upper pane' -n M-k \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-k' \
'select-pane -U'

bind -N 'focus right pane' -n M-l \
if-shell "tmx keybinds send_key_if '$vim_p' '$spf_p'" \
'send-keys M-l' \
'select-pane -R'

bind -N 'focus left pane' -n M-h \
if-shell "tmx keybinds send_key_if '$vim_p' '$spf_p'" \
'send-keys M-h' \
'select-pane -L' \

bind -N 'focus previous pane' -n M-o \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-o' \
'select-pane -l'

# force focus pane
bind -N 'force focus below pane' M-j select-pane -D
bind -N 'force focus upper pane' M-k select-pane -U
bind -N 'force focus right pane' M-l select-pane -R
bind -N 'force focus left pane' M-h select-pane -L
bind -N 'force focus previous pane' M-o select-pane -l
