# create/destroy panes
## normal mode
bind -N 'split window vertically' -n M-v \
if-shell "tmx keybinds" \
'send-keys M-v' \
'split-window -v'

bind -N 'split window horizontally' -n M-z \
if-shell "tmx keybinds" \
'send-keys M-z' \
'split-window -h'

bind -N 'kill pane' -n M-x \
if-shell "tmx keybinds" \
'send-keys M-x' \
'kill-pane'

## force create/destroy panes
bind -N 'force split window vertically' M-v split-window -v
bind -N 'force split window horizontally' M-z split-window -h
bind -N 'force kill pane' M-x kill-pane
