# normal mode
bind -N 'resize pane downward' -n M-C-j \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-C-j' \
'resize-pane -D 3'

bind -N 'resize pane upward' -n M-C-k \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-C-k' \
'resize-pane -U 3'

bind -N 'resize pane to the right' -n M-C-l \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-C-l' \
'resize-pane -R 5'

bind -N 'resize pane to the left' -n M-C-h \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-C-h' \
'resize-pane -L 5'

bind -N 'toggle pane zoom' -n M-C-z \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-C-z' \
'resize-pane -Z'

bind -N 'equlaize panes' -n M-= \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-=' \
'select-layout tiled'

# force resize pane
bind -N 'force resize pane downward' M-C-j resize-pane -D 3
bind -N 'force resize pane upward' M-C-k resize-pane -U 3
bind -N 'force resize pane to the right' M-C-l resize-pane -R 5
bind -N 'force resize pane to the left' M-C-h resize-pane -L 5
bind -N 'force toggle pane zoom' M-C-z resize-pane -Z
