# normal mode
bind -N 'swap with below pane' -n M-J \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-J' \
'swap-pane -d -t "{down-of}"'

bind -N 'swap with upper pane' -n M-K \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-K' \
'swap-pane -d -t "{up-of}"' \

bind -N 'swap with right pane' -n M-L \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-L' \
'swap-pane -d -t "{right-of}"'

bind -N 'swap with left pane' -n M-H \
if-shell "tmx keybinds send_key_if '$vim_p'" \
'send-keys M-H' \
'swap-pane -d -t "{left-of}"'

# force swap pane
bind -N 'force swap with below pane' M-J swap-pane -d -t '{down-of}'
bind -N 'force swap with upper pane' M-K swap-pane -d -t '{up-of}'
bind -N 'force swap with right pane' M-L swap-pane -d -t '{right-of}'
bind -N 'force swap with left pane' M-H swap-pane -d -t '{left-of}'
