bind -N 'switch pane to 1st window' 1 join-pane -h -t :1
bind -N 'switch pane to 2nd window' 2 join-pane -h -t :2
bind -N 'switch pane to 3rd window' 3 join-pane -h -t :3
bind -N 'switch pane to 4th window' 4 join-pane -h -t :4
bind -N 'switch pane to 5th window' 5 join-pane -h -t :5
bind -N 'switch pane to 6th window' 6 join-pane -h -t :6
bind -N 'switch pane to 7th window' 7 join-pane -h -t :7
bind -N 'switch pane to 8th window' 8 join-pane -h -t :8
bind -N 'switch pane to 9th window' 9 join-pane -h -t :9
bind -N 'switch pane to 10th window' 0 join-pane -h -t :10

bind -N 'move other pane in next window' b break-pane -b
