return {
	['j'] = 'MoveDown',
	['k'] = 'MoveUp',
	['q'] = 'Close',
	['<M-x>'] = 'Close',
	['<c-o>'] = 'OpenTree',
	['<c-g>'] = 'Command',
	['<c-h>'] = 'CommandHistory',
	['<c-r>'] = 'RefreshBuffer',
	['<c-s-r>'] = 'ShowRefs',
	['<c-p>'] = 'GoToParentRepo',

	['z1'] = 'Depth1',
	['z2'] = 'Depth2',
	['z3'] = 'Depth3',
	['z4'] = 'Depth4',
	['<tab>'] = 'Toggle',
	['s'] = 'Stage',
	['S'] = 'StageAll',
	['u'] = 'Unstage',
	['U'] = 'UnstageStaged',
	['X'] = 'Untrack',
	['r'] = 'Discard',

	['<c-cr>'] = 'PeekFile',
	['<cr>'] = 'GoToFile',
	['<c-z>'] = 'VSplitOpen',
	['<c-v>'] = 'SplitOpen',
	['<c-t>'] = 'TabOpen',

	['[h'] = 'GoToPreviousHunkHeader',
	[']h'] = 'GoToNextHunkHeader',
	['[o'] = 'OpenOrScrollUp',
	[']o'] = 'OpenOrScrollDown',
	['{'] = 'PeekUp',
	['}'] = 'PeekDown',
}
