bind = SUPER, SPACE, exec, tofi-drun | xargs hyprctl dispatch exec
binds = Super_L, C&P, exec, hyprpicker -na
bind = SUPER, V, exec, hyp_lunch_clipboard
bind = SUPER SHIFT, E, exec, hyp_select_emoji ~/personal/emojies
bind = SUPER ALT, S, exec, hyp_select_audio sink
bind = SUPER ALT SHIFT, S, exec, hyp_select_audio source
bind = SUPER, T, exec, ghostty
bind = SUPER, B, exec, qtb session start tmp
bind = SUPER, G, exec, heroic
