bind = SUPER, S, submap, screenshot
submap = screenshot

bind = SUPER, M, exec, hyp_screenshot output -a
bind = SUPER, W, exec, hyp_screenshot window -a
bind = SUPER SHIFT, M, exec, hyp_screenshot output
bind = SUPER SHIFT, W, exec, hyp_screenshot window 
bind = SUPER, R, exec, hyp_screenshot region

bind = SUPER, ESCAPE, submap, reset
submap = reset
