[backup]
type = local
description = seagate backup hard drive (2To)
nounc = false
copy_links = false
links = true
skip_likns = false
skip_specials = true
unicode_normalization = false
no_check_updated = false
one_file_system = false
case_sensitive = true
case_insensitive = false
no_clone = true
no_preallocate = false
no_sparse = false
no_set_modtime = false
time_type = mtime
