set -g @plugin 'dracula/tmux'

set -g @dracula-plugins " "
set -g @dracula-show-empty-plugins false

set -g @dracula-show-powerline true
set -g @dracula-show-edge-icons false

set -g @dracula-show-left-sep ''
set -g @dracula-show-right-sep ''
set -g @dracula-transparent-powerline-bg true
set -g @dracula-inverse-divider ''

set -g @dracula-show-left-icon "#S"
set -g @dracula-left-icon-padding 0

set -g @dracula-show-flags true
set -g @dracula-refresh-rate 5
set -g @dracula-border-contrast true

# don't even ask
set -g @dracula-colors "
white='#ffffff'
gray='#6272a4'
dark_gray='#fff0f9'
light_purple='#bd93f9'
dark_purple='#6272a4'
cyan='#8be9fd'
green='#D00050'
orange='#ffb86c'
red='#D00050'
pink='#ff7aca'
yellow='#ff7aca'
"
