set -g @plugin 'Morantron/tmux-fingers'

set -g @fingers-main-action ':copy:'
set -g @fingers-ctrl-action ':open:'
set -g @fingers-shift-action ':paste:'
set -g @fingers-alt-action ':copy:'

set -g @fingers-keyboard-layout dvorak
set -g @fingers-show-copied-notification 0
set -g @fingers-hint-position 'left'

set -g @fingers-hint-style fg=blue,bold,underscore
set -g @fingers-highlight-style fg=color6

set -g @fingers-selected-hint-style fg=blue,bold,underscore
set -g @fingers-selected-highlight-style fg=blue

set -g @fingers-backdrop-style fg=white

bind -n M-f run -b "#{@fingers-cli} start #{pane_id}"
bind M-f run -b "#{@fingers-cli} start #{pane_id} --mode jump"


