set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-dir '~/.local/state/tmux/ressurect'
set -g @resurrect-capture-pane-contents 'on'

set -g @resurrect-processes '\
"~btop->btop *" \
"~man->man *" \
"~nvim->vi *" \
"~less->less *" \
"~tail->tail *" \
'
