set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'M-s'
set -g @sessionx-prefix 'off'


set -g @sessionx-x-path '~/.config/tmux'

set -g @sessionx-custom-paths ''
set -g @sessionx-custom-paths-subdirectories 'false'


set -g @sessionx-preview-enabled 'true'
set -g @sessionx-preview-location 'top'
set -g @sessionx-preview-ratio '60%'

set -g @sessionx-window-height '90%'
set -g @sessionx-window-width '90%'

set -g @sessionx-layout 'reverse'

set -g @sessionx-prompt "󱝪 "
set -g @sessionx-pointer "▶ "

set -g @sessionx-ls-command 'ls'
set -g @sessionx-additional-options "--color pointer:9,spinner:92,marker:46"

set -g @sessionx-window-mode 'off'
set -g @sessionx-tree-mode 'off'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'

set -g @sessionx-fzf-builtin-tmux 'off'
set -g @sessionx-legacy-fzf-support 'off'
set -g @sessionx-fzf-marks-mode 'off'

set -g @sessionx-tmuxinator-mode 'off'
set -g @sessionx-filtered-sessions ''
set -g @sessionx-auto-accept 'off'

# keybinds
set -g @sessionx-bind-select-up 'ctrl-p'
set -g @sessionx-bind-select-down 'ctrl-n'
set -g @sessionx-bind-scroll-up 'ctrl-u'
set -g @sessionx-bind-scroll-down 'ctrl-d'

set -g @sessionx-bind-back 'ctrl-h'
set -g @sessionx-bind-rename-session 'ctrl-r'
set -g @sessionx-bind-kill-session 'ctrl-x'
set -g @sessionx-bind-abort 'ctrl-q'



set -g @sessionx-bind-delete-char 'ctrl-b'
set -g @sessionx-bind-fzf-marks 'ctrl-m'

set -g @sessionx-bind-window-mode 'ctrl-w'
set -g @sessionx-bind-tree-mode 'ctrl-t'
set -g @sessionx-bind-new-window 'ctrl-o'
set -g @sessionx-bind-configuration-path 'ctrl-c'
