confirm = ['enter', 'l']
cd_quit = ['Q'] # not used
quit = ['q','esc']
change_panel_mode = ['v']

open_zoxide = ['z']
open_command_line = [':']
open_help_menu = ['?']
open_spf_prompt = ['>']

list_down = ['j']
list_up = ['k']
page_down = ['d']
page_up = ['u']

focus_on_sidebar = ['b']
focus_on_process_bar = ['o']
focus_on_metadata = ['m']
close_file_panel = ['alt+x']
create_new_file_panel = ['alt+z']
next_file_panel = ['alt+l']
previous_file_panel = ['alt+h']
toggle_file_preview_panel = ['w']
toggle_footer = ['f']

open_sort_options_menu = ['s']
toggle_reverse_sort = ['S']
toggle_dot_file = ['.']
file_panel_item_create = ['n']
file_panel_item_rename = ['r']
pinned_directory = ['i']
paste_items = ['p']
copy_items = ['y']
copy_path = ['ctrl+y']
copy_present_working_directory = ['Y']
cut_items = ['c']
delete_items = ['x']
permanently_delete_items = ['X']

compress_file = ['a']
extract_file = ['A']
open_file_with_editor = ['e']
open_current_directory_with_editor = ['E']

# tying
confirm_typing = ['enter']
cancel_typing = ['esc']

# normal mode
parent_directory = ['h']
search_bar = ['/']

# selection mode
file_panel_select_mode_items_select_down = ['tab']
file_panel_select_mode_items_select_up = ['shift+tab']
file_panel_select_all_items = ['ctrl+a']
