follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
music_directory "~/personal/media/music"
playlist_directory "~/personal/media/music/playlists"
db_file "~/.local/share/database"
log_file "~/.local/share/mpd/log"
pid_file "~/.local/state/mpd/pid"
state_file "~/.local/state/mpd/state"
sticker_file "~/.local/share/mpd/sticker.sql"

auto_update "yes"
log_level "default"
bind_to_address "/tmp/mpd_socket"
restore_paused "yes"
zeroconf_enabled "yes"
zeroconf_name "MPD"
gapless_mp3_playback "yes"
save_absolute_paths_in_playlists "no"
metadata_to_use "artist,album,title,track,name,genre,date,composer,performer,disc"

audio_output_format "44100:16:2"
samplerate_converter "0"
replaygain "off"
replaygain_preamp "0"
volume_normalization "no"
audio_buffer_size "2048"
buffer_before_play "15"

connection_timeout "60"
max_connections "5"
max_playlist_length "4096"
max_command_list_size "2048"
max_output_buffer_size "8192"

audio_output {
	type "pulse"
	name "pulse"
}

audio_output {
	type "fifo"
	name "fifo"
	path "/tmp/mpd_fifo"
	format "44100:16:2"
}
