# server options
set default-terminal tmux-256color
set default-shell '/usr/bin/nu'
set escape-time 0
set editor '/sbin/nvim'
set exit-unattached off
set exit-empty on
set extended-keys on
set extended-keys-format csi-u
set focus-events on
set history-file ''
set set-clipboard on
set -a terminal-features 'xterm*:256,clipboard,extkeys,focus,hyperlinks,osc7,overline,RGB,mouse,strikethrough,usstyle,sync,title'

# session options
set -g activity-action none
set -g bell-action none
set -g visual-activity off
set -g visual-bell off
set -g display-time 3000
set -g key-table root
set -g mouse on
set -g message-line 0
set -g prefix M-t
set -g prefix-timeout 800
set -g renumber-windows on
set -g base-index 1
set -g default-command '/sbin/nu -e fastfetch'
set -g status-keys vi
set -g status-position top
set -g status-interval 5
set -g history-limit 50000
set -g copy-mode-selection-style fg=#1a102e,bg=#fff0f9

# window options
setw -g aggressive-resize on
set -g fill-character '░'
set -g monitor-activity on
set -g monitor-bell on
set -g mode-keys vi
set -g mode-style fg=#21222c,bg=#ffffff
set -g pane-base-index 1
set -g pane-border-indicators colour
set -g pane-border-lines heavy
set -g wrap-search on

# pane options
set -g allow-passthrough on
set -g allow-rename on
set -g allow-set-title on
set -g scroll-on-clear on
set -g alternate-screen on
set -g cursor-colour '#ffffff'
