source-file ~/.config/tmux/options.conf

# KEYBINDS
source-file ~/.config/tmux/keybinds/reset.conf
source-file ~/.config/tmux/keybinds/windows.conf
source-file ~/.config/tmux/keybinds/panes/swap.conf
source-file ~/.config/tmux/keybinds/panes/focus.conf
source-file ~/.config/tmux/keybinds/panes/other.conf
source-file ~/.config/tmux/keybinds/panes/resize.conf
source-file ~/.config/tmux/keybinds/panes/switch.conf
source-file ~/.config/tmux/keybinds/modes.conf
source-file ~/.config/tmux/keybinds/other.conf

# PLUGINS
source-file ~/.config/tmux/plugins_conf/dracula.conf
source-file ~/.config/tmux/plugins_conf/tmux_fzf.conf
source-file ~/.config/tmux/plugins_conf/sessionx.conf
source-file ~/.config/tmux/plugins_conf/fingers.conf
source-file ~/.config/tmux/plugins_conf/resurrect.conf
source-file ~/.config/tmux/plugins_conf/continuum.conf
source-file ~/.config/tmux/plugins_conf/tpm.conf
