[options]
BottomUp
SudoLoop = true
Devel
CleanAfter
Provides = all
CombinedUpgrade
BatchInstall
UpgradeMenu
SortBy = votes
SearchBy = name-desc
Limit = 0
CompletionInterval = 3

[bin]
Sudo = doas
Pager = bat --plain
BatFlags = --number
